language: csharp
mono: none
dotnet: 3.1.100

install:
    - sudo apt-get -qq update
    - sudo apt-get -qq install libmotif-dev libxmu-dev libxt-dev libfontconfig1-dev xvfb fonts-ipafont-gothic xfonts-intl-japanese

script:
    - dotnet restore
    - sudo fc-cache -v
    - cd TonNurakoTest
    - dotnet restore
    - dotnet build
    - ./headless.sh
