//
// ﾄﾝﾇﾗｺ
// 
// Widget
//
namespace TonNurako.Events
{
    /// <summary>
    /// 
    /// </summary>
    public enum CallReason {
        ACTIVATE = TonNurako.Motif.Constant.XmCR_ACTIVATE,
        APPLY = TonNurako.Motif.Constant.XmCR_APPLY,
        ARM = TonNurako.Motif.Constant.XmCR_ARM,
        BROWSE_SELECT = TonNurako.Motif.Constant.XmCR_BROWSE_SELECT,
        CANCEL = TonNurako.Motif.Constant.XmCR_CANCEL,
        CASCADING = TonNurako.Motif.Constant.XmCR_CASCADING,
        CLIPBOARD_DATA_DELETE = TonNurako.Motif.Constant.XmCR_CLIPBOARD_DATA_DELETE,
        CLIPBOARD_DATA_REQUEST = TonNurako.Motif.Constant.XmCR_CLIPBOARD_DATA_REQUEST,
        COLLAPSED = TonNurako.Motif.Constant.XmCR_COLLAPSED,
        COMMAND_CHANGED = TonNurako.Motif.Constant.XmCR_COMMAND_CHANGED,
        COMMAND_ENTERED = TonNurako.Motif.Constant.XmCR_COMMAND_ENTERED,
        CREATE = TonNurako.Motif.Constant.XmCR_CREATE,
        DECREMENT = TonNurako.Motif.Constant.XmCR_DECREMENT,
        DEFAULT_ACTION = TonNurako.Motif.Constant.XmCR_DEFAULT_ACTION,
        DISARM = TonNurako.Motif.Constant.XmCR_DISARM,
        DRAG = TonNurako.Motif.Constant.XmCR_DRAG,
        DRAG_DROP_FINISH = TonNurako.Motif.Constant.XmCR_DRAG_DROP_FINISH,
        DRAG_MOTION = TonNurako.Motif.Constant.XmCR_DRAG_MOTION,
        DRAG_START = TonNurako.Motif.Constant.XmCR_DRAG_START,
        DROP_FINISH = TonNurako.Motif.Constant.XmCR_DROP_FINISH,
        DROP_MESSAGE = TonNurako.Motif.Constant.XmCR_DROP_MESSAGE,
        DROP_SITE_ENTER = TonNurako.Motif.Constant.XmCR_DROP_SITE_ENTER,
        DROP_SITE_ENTER_MESSAGE = TonNurako.Motif.Constant.XmCR_DROP_SITE_ENTER_MESSAGE,
        DROP_SITE_LEAVE = TonNurako.Motif.Constant.XmCR_DROP_SITE_LEAVE,
        DROP_SITE_LEAVE_MESSAGE = TonNurako.Motif.Constant.XmCR_DROP_SITE_LEAVE_MESSAGE,
        DROP_SITE_MOTION_MESSAGE = TonNurako.Motif.Constant.XmCR_DROP_SITE_MOTION_MESSAGE,
        DROP_START = TonNurako.Motif.Constant.XmCR_DROP_START,
        END_JOB = TonNurako.Motif.Constant.XmCR_END_JOB,
        ENTER_CHILD = TonNurako.Motif.Constant.XmCR_ENTER_CHILD,
        EXECUTE = TonNurako.Motif.Constant.XmCR_EXECUTE,
        EXPANDED = TonNurako.Motif.Constant.XmCR_EXPANDED,
        EXPOSE = TonNurako.Motif.Constant.XmCR_EXPOSE,
        EXTENDED_SELECT = TonNurako.Motif.Constant.XmCR_EXTENDED_SELECT,
        FOCUS = TonNurako.Motif.Constant.XmCR_FOCUS,
        FOCUS_MOVED = TonNurako.Motif.Constant.XmCR_FOCUS_MOVED,
        GAIN_PRIMARY = TonNurako.Motif.Constant.XmCR_GAIN_PRIMARY,
        HELP = TonNurako.Motif.Constant.XmCR_HELP,
        INCREMENT = TonNurako.Motif.Constant.XmCR_INCREMENT,
        INPUT = TonNurako.Motif.Constant.XmCR_INPUT,
        LEAVE_CHILD = TonNurako.Motif.Constant.XmCR_LEAVE_CHILD,
        LOSE_PRIMARY = TonNurako.Motif.Constant.XmCR_LOSE_PRIMARY,
        LOSING_FOCUS = TonNurako.Motif.Constant.XmCR_LOSING_FOCUS,
        MAJOR_TAB = TonNurako.Motif.Constant.XmCR_MAJOR_TAB,
        MAP = TonNurako.Motif.Constant.XmCR_MAP,
        MINOR_TAB = TonNurako.Motif.Constant.XmCR_MINOR_TAB,
        MODIFYING_TEXT_VALUE = TonNurako.Motif.Constant.XmCR_MODIFYING_TEXT_VALUE,
        MOVING_INSERT_CURSOR = TonNurako.Motif.Constant.XmCR_MOVING_INSERT_CURSOR,
        MULTIPLE_SELECT = TonNurako.Motif.Constant.XmCR_MULTIPLE_SELECT,
        NONE = TonNurako.Motif.Constant.XmCR_NONE,
        NO_FONT = TonNurako.Motif.Constant.XmCR_NO_FONT,
        NO_MATCH = TonNurako.Motif.Constant.XmCR_NO_MATCH,
        NO_RENDITION = TonNurako.Motif.Constant.XmCR_NO_RENDITION,
        OBSCURED_TRAVERSAL = TonNurako.Motif.Constant.XmCR_OBSCURED_TRAVERSAL,
        OK = TonNurako.Motif.Constant.XmCR_OK,
        OPERATION_CHANGED = TonNurako.Motif.Constant.XmCR_OPERATION_CHANGED,
        PAGE_DECREMENT = TonNurako.Motif.Constant.XmCR_PAGE_DECREMENT,
        PAGE_INCREMENT = TonNurako.Motif.Constant.XmCR_PAGE_INCREMENT,
        PAGE_SCROLLER_DECREMENT = TonNurako.Motif.Constant.XmCR_PAGE_SCROLLER_DECREMENT,
        PAGE_SCROLLER_INCREMENT = TonNurako.Motif.Constant.XmCR_PAGE_SCROLLER_INCREMENT,
        PAGE_SETUP = TonNurako.Motif.Constant.XmCR_PAGE_SETUP,
        PDM_CANCEL = TonNurako.Motif.Constant.XmCR_PDM_CANCEL,
        PDM_EXIT_ERROR = TonNurako.Motif.Constant.XmCR_PDM_EXIT_ERROR,
        PDM_NONE = TonNurako.Motif.Constant.XmCR_PDM_NONE,
        PDM_OK = TonNurako.Motif.Constant.XmCR_PDM_OK,
        PDM_START_ERROR = TonNurako.Motif.Constant.XmCR_PDM_START_ERROR,
        PDM_START_PXAUTH = TonNurako.Motif.Constant.XmCR_PDM_START_PXAUTH,
        PDM_START_VXAUTH = TonNurako.Motif.Constant.XmCR_PDM_START_VXAUTH,
        PDM_UP = TonNurako.Motif.Constant.XmCR_PDM_UP,
        POST = TonNurako.Motif.Constant.XmCR_POST,
        PROTOCOLS = TonNurako.Motif.Constant.XmCR_PROTOCOLS,
        REPOST = TonNurako.Motif.Constant.XmCR_REPOST,
        RESIZE = TonNurako.Motif.Constant.XmCR_RESIZE,
        SELECT = TonNurako.Motif.Constant.XmCR_SELECT,
        SINGLE_SELECT = TonNurako.Motif.Constant.XmCR_SINGLE_SELECT,
        SPIN_FIRST = TonNurako.Motif.Constant.XmCR_SPIN_FIRST,
        SPIN_LAST = TonNurako.Motif.Constant.XmCR_SPIN_LAST,
        SPIN_NEXT = TonNurako.Motif.Constant.XmCR_SPIN_NEXT,
        SPIN_PRIOR = TonNurako.Motif.Constant.XmCR_SPIN_PRIOR,
        START_JOB = TonNurako.Motif.Constant.XmCR_START_JOB,
        TAB_SELECTED = TonNurako.Motif.Constant.XmCR_TAB_SELECTED,
        TAB_UNSELECTED = TonNurako.Motif.Constant.XmCR_TAB_UNSELECTED,
        TEAR_OFF_ACTIVATE = TonNurako.Motif.Constant.XmCR_TEAR_OFF_ACTIVATE,
        TEAR_OFF_DEACTIVATE = TonNurako.Motif.Constant.XmCR_TEAR_OFF_DEACTIVATE,
        TOP_LEVEL_ENTER = TonNurako.Motif.Constant.XmCR_TOP_LEVEL_ENTER,
        TOP_LEVEL_LEAVE = TonNurako.Motif.Constant.XmCR_TOP_LEVEL_LEAVE,
        TO_BOTTOM = TonNurako.Motif.Constant.XmCR_TO_BOTTOM,
        TO_TOP = TonNurako.Motif.Constant.XmCR_TO_TOP,
        UNMAP = TonNurako.Motif.Constant.XmCR_UNMAP,
        UPDATE_SHELL = TonNurako.Motif.Constant.XmCR_UPDATE_SHELL,
        UPDATE_TEXT = TonNurako.Motif.Constant.XmCR_UPDATE_TEXT,
        VALUE_CHANGED = TonNurako.Motif.Constant.XmCR_VALUE_CHANGED,
        VERIFY_TEXT = TonNurako.Motif.Constant.XmCR_VERIFY_TEXT,
        VERIFY_TEXT_FAILED = TonNurako.Motif.Constant.XmCR_VERIFY_TEXT_FAILED,
        WM_PROTOCOLS = TonNurako.Motif.Constant.XmCR_WM_PROTOCOLS
    }
}
