#ifndef _CLASSDEF_H_9F6F3F92_9548_4DBA_5927_805048C79EC1_
#define _CLASSDEF_H_9F6F3F92_9548_4DBA_5927_805048C79EC1_
#if !defined(_GNU_SOURCE)
#   define _GNU_SOURCE
#endif

#include <Xm/XmAll.h>

/* WidgetClass <-> TNK 苦しいﾏｯﾋﾟﾝｸﾞ*/
typedef enum
_tagTNK_WIDGET_CLASS {
    TNK_WIDGET_CLASS_INVALID = 0,
    TNK_xmArrowButtonGadgetClass = 1,
    TNK_xmArrowButtonWidgetClass = 2,
    TNK_xmBulletinBoardWidgetClass = 3,
    TNK_xmButtonBoxWidgetClass = 4,
    TNK_xmCascadeButtonGadgetClass = 5,
    TNK_xmCascadeButtonWidgetClass = 6,
    TNK_xmColorSelectorWidgetClass = 7,
    TNK_xmColumnWidgetClass = 8,
    TNK_xmComboBoxWidgetClass = 9,
    TNK_xmCommandWidgetClass = 10,
    TNK_xmContainerWidgetClass = 11,
    TNK_xmDataFieldWidgetClass = 12,
    TNK_xmDialogShellWidgetClass = 13,
    TNK_xmDisplayClass = 14,
    TNK_xmDragContextClass = 15,
    TNK_xmDragIconObjectClass = 16,
    TNK_xmDragOverShellWidgetClass = 17,
    TNK_xmDrawingAreaWidgetClass = 18,
    TNK_xmDrawnButtonWidgetClass = 19,
    TNK_xmDropDownWidgetClass = 20,
    TNK_xmDropSiteManagerObjectClass = 21,
    TNK_xmDropTransferObjectClass = 22,
    TNK_xmFileSelectionBoxWidgetClass = 23,
    TNK_xmFontSelectorWidgetClass = 24,
    TNK_xmFormWidgetClass = 25,
    TNK_xmFrameWidgetClass = 26,
    TNK_xmGadgetClass = 27,
    TNK_xmGrabShellWidgetClass = 28,
    TNK_xmHierarchyWidgetClass = 29,
    TNK_xmIconBoxWidgetClass = 30,
    TNK_xmIconButtonWidgetClass = 31,
    TNK_xmIconGadgetClass = 32,
    TNK_xmIconHeaderClass = 33,
    TNK_xmLabelGadgetClass = 34,
    TNK_xmLabelWidgetClass = 35,
    TNK_xmListWidgetClass = 36,
    TNK_xmMainWindowWidgetClass = 37,
    TNK_xmManagerWidgetClass = 38,
    TNK_xmMenuShellWidgetClass = 39,
    TNK_xmMessageBoxWidgetClass = 40,
    TNK_xmMultiListWidgetClass = 41,
    TNK_xmNotebookWidgetClass = 42,
    TNK_xmOutlineWidgetClass = 43,
    TNK_xmPanedWidgetClass = 44,
    TNK_xmPanedWindowWidgetClass = 45,
    TNK_xmPrimitiveWidgetClass = 46,
    TNK_xmPrintShellWidgetClass = 47,
    TNK_xmPushButtonGadgetClass = 48,
    TNK_xmPushButtonWidgetClass = 49,
    TNK_xmRowColumnWidgetClass = 50,
    TNK_xmScaleWidgetClass = 51,
    TNK_xmScreenClass = 52,
    TNK_xmScrollBarWidgetClass = 53,
    TNK_xmScrolledWindowWidgetClass = 54,
    TNK_xmSelectionBoxWidgetClass = 55,
    TNK_xmSeparatorGadgetClass = 56,
    TNK_xmSeparatorWidgetClass = 57,
    TNK_xmSimpleSpinBoxWidgetClass = 58,
    TNK_xmSpinBoxWidgetClass = 59,
    TNK_xmTabBoxWidgetClass = 60,
    TNK_xmTabStackWidgetClass = 61,
    TNK_xmTextFieldWidgetClass = 62,
    TNK_xmTextWidgetClass = 63,
    TNK_xmToggleButtonGadgetClass = 64,
    TNK_xmToggleButtonWidgetClass = 65,
    TNK_xmTreeWidgetClass = 66,
    TNK_WIDGET_CLASS_MAX = 67
}TNK_WIDGET_CLASS;

#endif
