#include "TonNurako.h"

Widget XmCreateArrowButton_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateArrowButton(parent, name, arglist, argcount);}
Widget XmCreateArrowButtonGadget_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateArrowButtonGadget(parent, name, arglist, argcount);}
Widget XmCreateBulletinBoard_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateBulletinBoard(parent, name, arglist, argcount);}
Widget XmCreateBulletinBoardDialog_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateBulletinBoardDialog(parent, name, arglist, argcount);}
Widget XmCreateButtonBox_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateButtonBox(parent, name, arglist, argcount);}
Widget XmCreateCascadeButton_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateCascadeButton(parent, name, arglist, argcount);}
Widget XmCreateCascadeButtonGadget_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateCascadeButtonGadget(parent, name, arglist, argcount);}
Widget XmCreateColorSelector_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateColorSelector(parent, name, arglist, argcount);}
Widget XmCreateColumn_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateColumn(parent, name, arglist, argcount);}
Widget XmCreateComboBox_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateComboBox(parent, name, arglist, argcount);}
Widget XmCreateCommand_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateCommand(parent, name, arglist, argcount);}
Widget XmCreateCommandDialog_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateCommandDialog(parent, name, arglist, argcount);}
Widget XmCreateContainer_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateContainer(parent, name, arglist, argcount);}
Widget XmCreateDataField_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateDataField(parent, name, arglist, argcount);}
Widget XmCreateDialogShell_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateDialogShell(parent, name, arglist, argcount);}
Widget XmCreateDragIcon_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateDragIcon(parent, name, arglist, argcount);}
Widget XmCreateDrawingArea_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateDrawingArea(parent, name, arglist, argcount);}
Widget XmCreateDrawnButton_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateDrawnButton(parent, name, arglist, argcount);}
Widget XmCreateDropDown_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateDropDown(parent, name, arglist, argcount);}
Widget XmCreateDropDownComboBox_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateDropDownComboBox(parent, name, arglist, argcount);}
Widget XmCreateDropDownList_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateDropDownList(parent, name, arglist, argcount);}
Widget XmCreateErrorDialog_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateErrorDialog(parent, name, arglist, argcount);}
Widget XmCreateFileSelectionBox_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateFileSelectionBox(parent, name, arglist, argcount);}
Widget XmCreateFileSelectionDialog_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateFileSelectionDialog(parent, name, arglist, argcount);}
Widget XmCreateFontSelector_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateFontSelector(parent, name, arglist, argcount);}
Widget XmCreateForm_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateForm(parent, name, arglist, argcount);}
Widget XmCreateFormDialog_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateFormDialog(parent, name, arglist, argcount);}
Widget XmCreateFrame_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateFrame(parent, name, arglist, argcount);}
Widget XmCreateGrabShell_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateGrabShell(parent, name, arglist, argcount);}
Widget XmCreateIconBox_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateIconBox(parent, name, arglist, argcount);}
Widget XmCreateIconButton_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateIconButton(parent, name, arglist, argcount);}
Widget XmCreateIconGadget_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateIconGadget(parent, name, arglist, argcount);}
Widget XmCreateIconHeader_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateIconHeader(parent, name, arglist, argcount);}
Widget XmCreateInformationDialog_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateInformationDialog(parent, name, arglist, argcount);}
Widget XmCreateLabel_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateLabel(parent, name, arglist, argcount);}
Widget XmCreateLabelGadget_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateLabelGadget(parent, name, arglist, argcount);}
Widget XmCreateList_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateList(parent, name, arglist, argcount);}
Widget XmCreateMainWindow_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateMainWindow(parent, name, arglist, argcount);}
Widget XmCreateMenuBar_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateMenuBar(parent, name, arglist, argcount);}
Widget XmCreateMenuShell_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateMenuShell(parent, name, arglist, argcount);}
Widget XmCreateMessageBox_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateMessageBox(parent, name, arglist, argcount);}
Widget XmCreateMessageDialog_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateMessageDialog(parent, name, arglist, argcount);}
Widget XmCreateMultiList_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateMultiList(parent, name, arglist, argcount);}
Widget XmCreateNotebook_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateNotebook(parent, name, arglist, argcount);}
Widget XmCreateOptionMenu_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateOptionMenu(parent, name, arglist, argcount);}
Widget XmCreateOutline_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateOutline(parent, name, arglist, argcount);}
Widget XmCreatePaned_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreatePaned(parent, name, arglist, argcount);}
Widget XmCreatePanedWindow_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreatePanedWindow(parent, name, arglist, argcount);}
Widget XmCreatePopupMenu_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreatePopupMenu(parent, name, arglist, argcount);}
Widget XmCreatePromptDialog_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreatePromptDialog(parent, name, arglist, argcount);}
Widget XmCreatePulldownMenu_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreatePulldownMenu(parent, name, arglist, argcount);}
Widget XmCreatePushButton_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreatePushButton(parent, name, arglist, argcount);}
Widget XmCreatePushButtonGadget_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreatePushButtonGadget(parent, name, arglist, argcount);}
Widget XmCreateQuestionDialog_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateQuestionDialog(parent, name, arglist, argcount);}
Widget XmCreateRadioBox_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateRadioBox(parent, name, arglist, argcount);}
Widget XmCreateRowColumn_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateRowColumn(parent, name, arglist, argcount);}
Widget XmCreateScale_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateScale(parent, name, arglist, argcount);}
Widget XmCreateScrollBar_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateScrollBar(parent, name, arglist, argcount);}
Widget XmCreateScrolledList_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateScrolledList(parent, name, arglist, argcount);}
Widget XmCreateScrolledText_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateScrolledText(parent, name, arglist, argcount);}
Widget XmCreateScrolledWindow_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateScrolledWindow(parent, name, arglist, argcount);}
Widget XmCreateSelectionBox_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateSelectionBox(parent, name, arglist, argcount);}
Widget XmCreateSelectionDialog_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateSelectionDialog(parent, name, arglist, argcount);}
Widget XmCreateSeparator_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateSeparator(parent, name, arglist, argcount);}
Widget XmCreateSeparatorGadget_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateSeparatorGadget(parent, name, arglist, argcount);}
Widget XmCreateSimpleCheckBox_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateSimpleCheckBox(parent, name, arglist, argcount);}
Widget XmCreateSimpleMenuBar_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateSimpleMenuBar(parent, name, arglist, argcount);}
Widget XmCreateSimpleOptionMenu_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateSimpleOptionMenu(parent, name, arglist, argcount);}
Widget XmCreateSimplePopupMenu_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateSimplePopupMenu(parent, name, arglist, argcount);}
Widget XmCreateSimplePulldownMenu_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateSimplePulldownMenu(parent, name, arglist, argcount);}
Widget XmCreateSimpleRadioBox_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateSimpleRadioBox(parent, name, arglist, argcount);}
Widget XmCreateSimpleSpinBox_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateSimpleSpinBox(parent, name, arglist, argcount);}
Widget XmCreateSpinBox_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateSpinBox(parent, name, arglist, argcount);}
Widget XmCreateTabBox_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateTabBox(parent, name, arglist, argcount);}
Widget XmCreateTabStack_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateTabStack(parent, name, arglist, argcount);}
Widget XmCreateTemplateDialog_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateTemplateDialog(parent, name, arglist, argcount);}
Widget XmCreateText_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateText(parent, name, arglist, argcount);}
Widget XmCreateTextField_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateTextField(parent, name, arglist, argcount);}
Widget XmCreateToggleButton_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateToggleButton(parent, name, arglist, argcount);}
Widget XmCreateToggleButtonGadget_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateToggleButtonGadget(parent, name, arglist, argcount);}
Widget XmCreateTree_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateTree(parent, name, arglist, argcount);}
Widget XmCreateWarningDialog_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateWarningDialog(parent, name, arglist, argcount);}
Widget XmCreateWorkArea_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateWorkArea(parent, name, arglist, argcount);}
Widget XmCreateWorkingDialog_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XmCreateWorkingDialog(parent, name, arglist, argcount);}
Widget XmCreateHierarchy_TNK(Widget parent, String name, ArgList arglist,Cardinal argcount) { return XtCreateWidget(name, xmHierarchyWidgetClass, parent, arglist, argcount);}
